### ISSUE TITLE
Open source for the firmware

### ISSUE THREAD

**Issue by vitficl** [skot/bitcart#1]
Hello all, I would like to ask if you have also open source for the firmware?

**Comment by DCentralTech** [comment]
​It's not available yet       Anthony Desjardins  Équipe de D-Central | D-Central team  Co-fondateur | Co-Founder   _________________________________________________________        1 (855) 753.9997      4479 Desserte Nord Autoroute 440, Laval, QC H7P 6E2      ***@***.***                            
                           
                            On
                            Fri, 6 Oct at 10:08 AM
                            ,  skot/bitcart ***@***.***>  wrote:
                             
 Hello all, I would like to ask if you have also open source for the firmware?

**Comment by skot** [comment]
Yes, the firmware will be open source! It's not ready yet though. I'll add a link to the readme here when it is.
